WHITESPACE = _{ " " | "\t" | "\n" }

lambdaexpr = _{
    Goal
}

Goal = { "Goal(" ~ lambdaexpr ~ "," ~ usize ~ ")" }

// Define the grammar for the OP enum
OP = _{
    Load
    | Use
    | Intro
    | Assumption
    | Apply
}

Load = { "Load(" ~ string ~ ")" }
Use = { "Use(" ~ string ~ ")" }
Intro = { "Intro" }
Assumption = { "Assumption" }
Apply = { "Apply(" ~ string ~ ")" }

string = { "\"" ~ ASCII_ALPHANUMERIC+ ~ "\"" }
usize = @{ ASCII_DIGIT+ }